site_name: Trabalho1_Rec_Padroes
<<<<<<< HEAD
site_author: Lucas José Lemos Braz

nav:
  - Home: index.md
  - API Reference: reference.md

plugins:
  - search
  - mkdocstrings
=======
# 
site_author: Lucas José Lemos Braz
# 
>>>>>>> origin/main
